---

# tasks file for Sudoers_Gatto

- name: "GProfesores pueden usar sudo sin contraseña"
  become: yes
  copy:
    dest: /etc/sudoers.d/GProfesores
    content: "GProfesores ALL=(ALL) NOPASSWD:ALL"

