---
# tasks file for 2PRecuperatorio

 - name: "Crear directorios en /tmp/alumno/"
   file:
     path: "/tmp/alumno/{{ item }}"
     state: directory
     mode: '0775'
     recurse: yes
   with_items:
     - "log"
     - "config"


 - name: "Crear archivo datos.txt"
   template:
     src: template_01.j2
     dest: /tmp/alumno/datos.txt


